<?php

namespace app\components;
use \yii\base\widget;
class MenuWidget extends Widget
{

    public $tpl;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->tpl === null) {
            $this->tpl = 'menu';
        }
        $this->tpl .= '.php';
    }

    public function run() {
        return $this->tpl;
    }

}